kumuluzee:
  datasources:
    - jndi-name: jdbc/CustomersDS
      connection-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      pool:
        max-size: 2
  persistence-units:
    - name: "kumuluzee-acme"
      continue-on-error: false